name: Docker Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build god-mode image
        run: docker build -f dashbashdocker -t docker-god:latest .
      - name: Check size
        run: docker images docker-god:latest